[pytest]
DJANGO_SETTINGS_MODULE = book_corner.settings
python_files = test_*.py *_tests.py
addopts = --tb=short --strict-markers --disable-warnings
markers =
    selenium: marks tests as selenium tests (deselect with '-m "not selenium"')
    slow: slow tests
